### PR TITLE
[WIP] Use Selenium to run benchmarks headless

### PR DESCRIPTION
**Pull request by PaulBGD**
Includes #6, for some reason.

Things left 
- add `npm run selenium` (needs to build benchmarks as well)
- pass options to the browsers, such as `--headless` or `--no-gpu` for Chrome.
- format `selenium/run.js` to consistently match style of svelte's main codebase
- move `runCode()` out of `selenium/run.js`
- figure out a way to share more code between selenium and running in browser
- generating charts would be cool, implementing this with travis then having a bot that automatically posts charts on the PRs would be nice
- not really a thing for this PR, but running svelte's tests in selenium would probably find more bugs than `jsdom` (as well it'd test cross-browser compatibility)

### CODE REVIEW

**Comment by PaulBGD** [comment]
Sample output (without color indicating the fastest times):

```
create-large-table (firefox)

          version    create:cold    create:warm       run:cold       run:warm   destroy:cold   destroy:warm
           1.17.0         28.995         20.737          0.000          0.000          1.810         10.510
           1.16.0         27.545         21.070          0.000          0.000          2.010         11.504
           1.15.1         28.100         19.895          0.000          0.000          1.655         11.251
           1.15.0         27.725         19.580          0.000          0.000          1.795         11.224
           1.14.1         29.495         23.253          0.000          0.000          1.840         14.489
           1.13.7         26.100         21.401          0.000          0.000          1.685         12.591
           1.12.1         27.775         21.051          0.000          0.000          1.655         11.613
           1.11.4         29.705         23.686          0.000          0.000          1.835         11.918
           1.10.3         26.250         19.799          0.000          0.000          1.995         10.944
            1.9.1         28.025         20.741          0.000          0.000          2.180         11.633
            1.8.1         27.840         19.463          0.000          0.000          2.380         10.486
             1.7.1 "Duplicated import 'get'", "Duplicated import 'get'", "Duplicated import 'get'", "Duplicated import 'get'", "Duplicated import 'get'"
           1.6.11         26.010         21.154          0.000          0.000          1.930         10.468
            1.5.0         27.085         20.659          0.000          0.000          2.335         10.868
            1.4.0         52.510         20.804          0.000          0.000          2.085         10.481
            1.3.1         51.390         19.730          0.000          0.000          1.970         11.389
            1.2.5         52.035         19.889          0.000          0.000          1.765         10.490
            1.1.3         56.530         20.550          0.000          0.000          1.975         11.759
            1.0.7         53.715         28.943          0.000          0.000          1.800         11.592



dbmonster (firefox)

          version    create:cold    create:warm       run:cold       run:warm   destroy:cold   destroy:warm
           1.17.0         27.835         13.709          8.040          4.242          5.625          6.026
           1.16.0         26.000         13.655          8.290          4.386          5.990          6.746
           1.15.1         26.295         14.105          8.070          3.619          5.340          6.935
           1.15.0         26.910         14.174          8.595          4.265          5.320          6.710
           1.14.1         29.605         16.817          9.320          4.851          6.495          8.370
           1.13.7         26.085         14.610          8.335          3.341          5.865          6.638
           1.12.1         30.955         16.856          7.550          4.839          5.420          6.357
           1.11.4         30.830         16.658          8.510          4.112          6.320          6.358
           1.10.3         32.250         16.471          8.470          3.850          5.430          6.124
            1.9.1         30.120         21.747          8.435          5.994          5.850          7.251
            1.8.1         30.955         16.661          9.540          4.174          5.975          6.344
             1.7.1 "Duplicated import 'get'", "Duplicated import 'get'", "Duplicated import 'get'", "Duplicated import 'get'", "Duplicated import 'get'"
           1.6.11         29.875         19.421          8.925          4.439          7.500          6.374
            1.5.0         31.475         16.683         11.770          6.839          5.555          6.394
            1.4.0         39.480         17.477         12.135          6.690          5.500          7.003
            1.3.1         38.165         18.607         11.830          8.143          5.810          7.824
            1.2.5         37.780         15.684         11.385          7.529          5.875          6.662
            1.1.3         38.285         16.979         12.160          8.083          7.135          6.718
            1.0.7         38.815         14.954         12.205          7.069          5.380          7.174



hello-world (firefox)

          version    create:cold    create:warm       run:cold       run:warm   destroy:cold   destroy:warm
           1.17.0          0.740          0.136          0.340          0.075          0.140          0.088
           1.16.0          0.740          0.118          0.345          0.073          0.140          0.120
           1.15.1          0.645          0.131          0.420          0.089          0.135          0.111
           1.15.0          0.715          0.148          0.305          0.094          0.140          0.101
           1.14.1          0.705          0.142          0.315          0.082          0.155          0.126
           1.13.7          0.745          0.136          0.305          0.070          0.140          0.102
           1.12.1          0.765          0.148          0.345          0.101          0.145          0.147
           1.11.4          0.760          0.124          0.355          0.108          0.145          0.108
           1.10.3          0.930          0.126          0.630          0.100          0.160          0.095
            1.9.1          0.795          0.140          0.635          0.109          0.145          0.119
            1.8.1          0.785          0.120          0.575          0.113          0.145          0.127
             1.7.1 "Duplicated import 'get'", "Duplicated import 'get'", "Duplicated import 'get'", "Duplicated import 'get'", "Duplicated import 'get'"
           1.6.11          0.790          0.146          0.550          0.124          0.135          0.129
            1.5.0          0.795          0.137          0.475          0.105          0.140          0.124
            1.4.0          1.120          0.178          0.655          0.105          0.195          0.125
            1.3.1          0.935          0.187          0.640          0.096          0.160          0.115
            1.2.5          0.770          0.150          0.480          0.103          0.125          0.116
            1.1.3          0.760          0.125          0.500          0.117          0.130          0.113
            1.0.7          0.670          0.121          0.495          0.101          0.125          0.100
```

Which reminds me, we should skip `1.7.1`.

**Comment by PaulBGD** [comment]
Actually there's still more I have to do, the big one is that I have to add the option to use Sauce Labs instead of a local selenium instance.

**Comment by Rich-Harris** [comment]
Ah shit, sorry! Was over-excited — missed the [WIP]. Should I revert?

**Comment by PaulBGD** [comment]
No worries, this technically works as-is. I can add support for saucelabs in master.

**Pull request merged**
